heat_template_version: 2015-10-15

resources:
  server_01:
    type: OS::Nova::Server
    properties:
      name: test
      image: CentOS 7 (PVHVM) (Orchestration)
      flavor: 1 GB General Purpose v1
      key_name: etaranov
      networks:
      - network: 11111111-1111-1111-1111-111111111111
  server_01_public_ip:
    type: Rackspace::RackConnect::PublicIP
    depends_on:
    - server_01
    properties:
      server_id: { get_resource: server_01 }
